libname myAss "/home/u61813922/Assignment";

/* Date Entry */
data myAss.table4;
input Gender $1-7  			/* Respondent gender whether male or female */
	Age $8-21  				/* Respondent range of Age */
	Occupation $22-30  	 	/* Respondent Occupation */
	Salary $31-43	   		/* Respondent Monthly Salary */
	Category $44-78  		/* Respondent categories the item / product such as shoes, pants, shirts, accessories*/
	Series $79-89  			/* Respondent choose the favorite series shoes like Ultraboost, Yeezy*/
	Often $90-108  			/* Respondent how often purchase the product such as few times a year */
	Budget $109-126  		/* Respondent how many budget such as below 500*/
	Factor $127-164  		/* What is the factor to lead respondent buy this product such as promotions, quality*/
	Frequently $165-176  	/* Respondent how frequently use the product that purchased like daily, weekly*/
	Purchase $177-190 	 	/* How respondent purchase the product such as online, reatil store */
	Recognition $191-267 	/* How respondent know about the product like social media*/
	Purpose $268-310  		/* What is the purpose purchase the product like jogging*/
	Recommend $311-321  	/* Will respondent recomment Adidas product to people like family */
	Rating; 				/* Rate the product */
	
datalines;
Female        18-25    Student  Below 1000 Accessories (Exp : Cap, Sock, Bag)  Superstar   Few times a year   RM 500 - RM 800          Appearance, Promotions, Price      Weekly       Online                                           Social Media (Facebook, Instagram)                      Running, Gym, Outdoor     Maybe       8
Female        26-35   Employee  Above 4000                              Shoes Stan Smith   Yearly and above   RM 500 - RM 800                                  Price     Monthly Retail Store                                           Social Media (Facebook, Instagram)                                    Outdoor     Maybe       6
  Male        26-35   Employee 1000 - 2000                             Shirts Stan Smith   Yearly and above      Below RM 500                             Promotions       Daily Retail Store                                           Social Media (Facebook, Instagram)                                    Outdoor     Maybe       8
Female        18-25    Student  Below 1000                              Shoes Stan Smith   Yearly and above      Below RM 500                 Promotions, Appearance       Daily Retail Store Social Media (Facebook, Instagram), Advertisement, Friends or Family, Events                                    Outdoor     Maybe       8
Female        26-35   Employee 1000 - 2000                             Shirts    Ozweego   Few times a year      Below RM 500                             Appearance     Monthly Retail Store                            Social Media (Facebook, Instagram), Advertisement                                    Outdoor       Yes       8
  Male        18-25    Student 1000 - 2000                              Shoes      Yeezy   Yearly and above RM 1200 and above                                Quality      Weekly Retail Store         Social Media (Facebook, Instagram), Advertisement, Friends or Family                      Gym, Jogging, Running       Yes       7
  Male        18-25    Student  Below 1000                              Shoes Stan Smith   Yearly and above      Below RM 500             Price, Quality, Promotions      Weekly Retail Store         Social Media (Facebook, Instagram), Advertisement, Friends or Family                               Gym, Outdoor     Maybe       6
Female        18-25    Student  Below 1000                              Shoes Stan Smith   Yearly and above      Below RM 500        Quality, Promotions, Appearance       Daily Retail Store                            Social Media (Facebook, Instagram), Advertisement                           Running, Outdoor       Yes       7
  Male        18-25    Student 2000 - 4000                              Shoes Ultraboost   Few times a year   RM 500 - RM 800                    Quality, Appearance     Monthly Retail Store                    Social Media (Facebook, Instagram), Advertisement, Events               Running, Basketball, Outdoor       Yes       8
  Male        26-35   Employee 1000 - 2000                              Shoes Ultraboost   Yearly and above      Below RM 500                                Quality      Weekly Retail Store                                           Social Media (Facebook, Instagram)               Jogging, Running, Basketball       Yes       8
Female        26-35    Student  Below 1000                              Shoes Stan Smith   Yearly and above      Below RM 500                                  Price      Yearly Retail Store                                                            Friends or Family                                    Outdoor       Yes       8
  Male        18-25    Student  Below 1000                              Shoes  Superstar   Few times a year      Below RM 500                      Price, Promotions       Daily Retail Store                                                        Advertisement, Events                           Jogging, Outdoor        No       8
Female        18-25    Student  Below 1000                              Shoes  Superstar   Few times a year      Below RM 500                             Promotions      Weekly       Online         Social Media (Facebook, Instagram), Advertisement, Friends or Family                                    Running       Yes       9
  Male        18-25    Student  Below 1000                              Shoes Ultraboost Every 2 to 3 month  RM 800 - RM 1200             Price, Quality, Appearance      Yearly       Online                            Social Media (Facebook, Instagram), Advertisement             Gym, Jogging, Running, Outdoor       Yes       5
Female        18-25    Student  Below 1000                             Shirts Ultraboost   Yearly and above   RM 500 - RM 800                    Quality, Promotions      Weekly Retail Store                Social Media (Facebook, Instagram), Friends or Family, Events                               Gym, Running       Yes       8
Female        26-35   Employee  Above 4000                              Shoes Ultraboost   Yearly and above  RM 800 - RM 1200        Quality, Promotions, Appearance     Monthly Retail Store                            Social Media (Facebook, Instagram), Advertisement             Gym, Jogging, Running, Outdoor       Yes       8
Female        18-25    Student  Below 1000                              Shoes Ultraboost   Yearly and above      Below RM 500 Price, Quality, Promotions, Appearance      Weekly Retail Store                                                                Advertisement                                    Outdoor       Yes      10
Female        26-35   Employee 2000 - 4000                              Shoes Stan Smith   Few times a year      Below RM 500 Price, Quality, Promotions, Appearance      Yearly Retail Store                                                            Friends or Family                                    Outdoor       Yes       8
Female        18-25    Student  Below 1000 Accessories (Exp : Cap, Sock, Bag) Ultraboost   Yearly and above      Below RM 500                      Price, Promotions     Monthly Retail Store                                                            Friends or Family                                    Jogging     Maybe       6
  Male        18-25    Student  Below 1000                              Shoes Ultraboost   Yearly and above      Below RM 500 Price, Quality, Promotions, Appearance      Weekly Retail Store                                             Advertisement, Friends or Family                                    Jogging     Maybe       8
  Male        18-25    Student  Below 1000                              Shoes      Yeezy       Once a month   RM 500 - RM 800             Price, Quality, Promotions      Yearly Retail Store                                           Social Media (Facebook, Instagram)                                    Running       Yes       8
  Male        18-25    Student  Below 1000                              Shoes Ultraboost   Yearly and above      Below RM 500             Price, Quality, Appearance      Weekly Retail Store         Social Media (Facebook, Instagram), Advertisement, Friends or Family                      Gym, Jogging, Running       Yes       9
Female        18-25    Student  Below 1000                              Shoes Ultraboost   Yearly and above      Below RM 500 Price, Quality, Promotions, Appearance      Yearly Retail Store         Social Media (Facebook, Instagram), Advertisement, Friends or Family                                    Outdoor     Maybe       7
  Male        18-25    Student  Below 1000                              Shoes Ultraboost   Yearly and above      Below RM 500 Price, Quality, Promotions, Appearance      Weekly Retail Store                                                                       Events Gym, Jogging, Running, Basketball, Outdoor       Yes       9
Female        18-25    Student  Below 1000                              Shoes Ultraboost   Yearly and above      Below RM 500                         Price, Quality       Daily Retail Store                                                            Friends or Family                           Jogging, Outdoor       Yes       8
  Male        18-25    Student  Below 1000                              Shoes Ultraboost   Yearly and above      Below RM 500                    Quality, Appearance       Daily       Online         Social Media (Facebook, Instagram), Advertisement, Friends or Family                  Jogging, Running, Outdoor       Yes       8
  Male        18-25    Student  Below 1000                              Shoes  Superstar Every 2 to 3 month   RM 500 - RM 800 Price, Quality, Promotions, Appearance     Monthly       Online Social Media (Facebook, Instagram), Advertisement, Friends or Family, Events                   Gym, Jogging, Basketball     Maybe       8
  Male        18-25    Student  Below 1000 Accessories (Exp : Cap, Sock, Bag) Stan Smith   Few times a year      Below RM 500                             Appearance      Weekly       Online                            Social Media (Facebook, Instagram), Advertisement                                    Outdoor     Maybe       6
Female        18-25    Student  Below 1000                              Shoes      Yeezy   Yearly and above      Below RM 500                    Quality, Appearance      Yearly Retail Store                            Social Media (Facebook, Instagram), Advertisement                                    Outdoor       Yes       8
Female        18-25   Employee 2000 - 4000                              Shoes Ultraboost   Yearly and above      Below RM 500                             Promotions      Yearly Retail Store         Social Media (Facebook, Instagram), Advertisement, Friends or Family                           Running, Outdoor     Maybe       5
  Male        18-25    Student 1000 - 2000                              Shoes Stan Smith   Few times a year   RM 500 - RM 800                    Quality, Appearance      Weekly Retail Store Social Media (Facebook, Instagram), Advertisement, Friends or Family, Events                                    Outdoor       Yes       8
Female        18-25    Student  Below 1000                              Shoes  Superstar   Yearly and above      Below RM 500                    Quality, Promotions Fortnightly Retail Store         Social Media (Facebook, Instagram), Advertisement, Friends or Family                                        Gym     Maybe       7
Female        18-25   Employee  Above 4000                             Shirts Ultraboost   Few times a year   RM 500 - RM 800        Quality, Promotions, Appearance Fortnightly       Online                Social Media (Facebook, Instagram), Friends or Family, Events                        Running, Basketball       Yes       8
  Male 36 and above    Retired  Above 4000                              Pants    Ozweego   Yearly and above  RM 800 - RM 1200                 Promotions, Appearance     Monthly Retail Store                                                    Friends or Family, Events                                    Outdoor       Yes       9
Female 36 and above    Retired 2000 - 4000 Accessories (Exp : Cap, Sock, Bag) Stan Smith   Few times a year  RM 800 - RM 1200        Quality, Promotions, Appearance      Weekly Retail Store                                                    Friends or Family, Events                  Jogging, Running, Outdoor       Yes       9
  Male        18-25    Student  Below 1000                              Shoes Ultraboost   Yearly and above      Below RM 500                    Quality, Appearance      Weekly Retail Store                                           Social Media (Facebook, Instagram)                                    Outdoor     Maybe       8
  Male        18-25    Student  Below 1000                              Pants    Ozweego   Yearly and above      Below RM 500                      Price, Appearance      Weekly       Online                                           Social Media (Facebook, Instagram)                                    Jogging       Yes      10
Female        18-25    Student 1000 - 2000 Accessories (Exp : Cap, Sock, Bag)  Superstar   Few times a year   RM 500 - RM 800                    Quality, Promotions      Weekly Retail Store                            Social Media (Facebook, Instagram), Advertisement                                        Gym       Yes       8
Female 36 and above    Retired  Above 4000 Accessories (Exp : Cap, Sock, Bag) Stan Smith Every 2 to 3 month RM 1200 and above                    Quality, Appearance       Daily       Online Social Media (Facebook, Instagram), Advertisement, Friends or Family, Events Gym, Jogging, Running, Basketball, Outdoor     Maybe      10
Female        18-25    Student  Below 1000                              Shoes Ultraboost   Yearly and above   RM 500 - RM 800 Price, Quality, Promotions, Appearance      Weekly Retail Store                        Social Media (Facebook, Instagram), Friends or Family                                    Outdoor     Maybe       7
Female        18-25    Student 1000 - 2000                              Shoes Ultraboost   Yearly and above   RM 500 - RM 800             Price, Quality, Appearance       Daily Retail Store         Social Media (Facebook, Instagram), Advertisement, Friends or Family                           Running, Outdoor       Yes       9
  Male        18-25    Student  Below 1000                              Shoes Ultraboost   Yearly and above   RM 500 - RM 800                    Quality, Promotions      Yearly Retail Store                            Social Media (Facebook, Instagram), Advertisement                           Running, Outdoor       Yes       9
  Male        18-25    Student 1000 - 2000                              Shoes    Ozweego   Few times a year   RM 500 - RM 800                 Promotions, Appearance      Weekly       Online                                                    Friends or Family, Events                        Running, Basketball     Maybe      10
Female 36 and above    Retired 1000 - 2000                              Shoes      Yeezy   Few times a year  RM 800 - RM 1200        Quality, Promotions, Appearance Fortnightly Retail Store                Social Media (Facebook, Instagram), Friends or Family, Events                      Gym, Running, Outdoor       Yes       9
  Male 36 and above   Employee  Above 4000                              Shoes  Superstar Every 2 to 3 month RM 1200 and above                    Quality, Promotions     Monthly Retail Store                                                    Friends or Family, Events                               Gym, Outdoor       Yes      10
  Male        18-25    Student  Below 1000                             Shirts Ultraboost   Yearly and above      Below RM 500                                  Price      Weekly Retail Store                                                            Friends or Family                                    Outdoor     Maybe       8
  Male        18-25    Student  Below 1000 Accessories (Exp : Cap, Sock, Bag)    Ozweego   Yearly and above   RM 500 - RM 800 Price, Quality, Promotions, Appearance       Daily Retail Store                            Social Media (Facebook, Instagram), Advertisement                           Jogging, Running       Yes       9
Female        18-25    Student  Below 1000                              Shoes  Superstar   Yearly and above   RM 500 - RM 800 Price, Quality, Promotions, Appearance      Weekly Retail Store                                           Social Media (Facebook, Instagram)                                    Outdoor     Maybe      10
  Male        18-25    Student  Below 1000                              Pants      Yeezy   Few times a year      Below RM 500                         Price, Quality       Daily       Online                                           Social Media (Facebook, Instagram)                           Running, Outdoor     Maybe       9
  Male        18-25    Student  Below 1000 Accessories (Exp : Cap, Sock, Bag) Stan Smith Every 2 to 3 month      Below RM 500                    Quality, Promotions       Daily Retail Store                            Social Media (Facebook, Instagram), Advertisement                               Gym, Jogging        No       9
  ;
  run;
  
proc print data = myAss.table1; 	/* Print the results */
run;