libname myAss "/home/u61813922/Assignment";

data myAss.table3;
input gender $1-7  			/* Respondent gender whether male or female */
	age $8-21  				/* Respondent range of Age */
	occupation $22-30  	 	/* Respondent Occupation */
	salary $31-43	   		/* Respondent Monthly Salary */
	category $44-78  		/* Respondent categories the item / product such as shoes, pants, shirts, accessories*/
	series $79-89  			/* Respondent choose the favorite series shoes like Ultraboost, Yeezy*/
	often $90-108  			/* Respondent how often purchase the product such as few times a year */
	budget $109-126  		/* Respondent how many budget such as below 500*/
	factor $127-164  		/* What is the factor to lead respondent buy this product such as promotions, quality*/
	requently $165-176  	/* Respondent how frequently use the product that purchased like daily, weekly*/
	purchase $177-190 	 	/* How respondent purchase the product such as online, reatil store */
	recognition $191-267 	/* How respondent know about the product like social media*/
	purpose $268-310  		/* What is the purpose purchase the product like jogging*/
	recommend $311-321  	/* Will respondent recomment Adidas product to people like family */
	rating; 				/* Rate the product */
	
datalines;
  Male Less than 18    Student  Below 1000                              Shoes Ultraboost   Few times a year RM 1200 and above                             Appearance Fortnightly Retail Store                                                                       Events                               Gym, Jogging       Yes       9
Female 36 and above    Student  Below 1000                             Shirts Ultraboost Every 2 to 3 month   RM 500 - RM 800                         Quality, Price      Weekly Retail Store                                                                       Events                                        Gym        No       7
  Male 36 and above   Employee  Below 1000                              Pants Stan Smith Every 2 to 3 month RM 1200 and above                                Quality      Weekly Retail Store                                                            Friends or Family                                 Basketball       Yes       9
  Male        18-25    Student  Below 1000 Accessories (Exp : Cap, Sock, Bag)  Superstar       Once a month      Below RM 500                                Quality     Monthly       Online                                                                       Events                           Running, Outdoor        No       7
  Male        26-35   Employee  Below 1000                             Shirts Stan Smith Every 2 to 3 month  RM 800 - RM 1200                      Promotions, Price     Monthly       Online                                           Social Media (Facebook, Instagram)                                    Outdoor        No       6
Female        26-35   Employee  Above 4000                              Pants    Ozweego   Few times a year  RM 800 - RM 1200        Appearance, Promotions, Quality     Monthly Retail Store                                           Social Media (Facebook, Instagram)                  Running, Jogging, Outdoor        No       9
Female        26-35    Student  Below 1000                             Shirts  Superstar   Few times a year      Below RM 500             Quality, Price, Appearance Fortnightly       Online                                           Social Media (Facebook, Instagram)                   Running, Gym, Basketball        No       8
  Male 36 and above   Employee 2000 - 4000 Accessories (Exp : Cap, Sock, Bag) Ultraboost Every 2 to 3 month      Below RM 500                                  Price     Monthly Retail Store                                           Social Media (Facebook, Instagram)                                 Basketball     Maybe       6
Female        26-35    Student  Below 1000                              Pants      Yeezy   Yearly and above      Below RM 500          Price, Appearance, Promotions Fortnightly Retail Store                                                                       Events                           Jogging, Outdoor     Maybe       6
  Male Less than 18    Student 2000 - 4000                              Pants    Ozweego       Once a month      Below RM 500                             Appearance     Monthly Retail Store                                           Social Media (Facebook, Instagram)               Outdoor, Jogging, Basketball        No       9
Female        18-25    Student  Below 1000                              Pants    Ozweego Every 2 to 3 month      Below RM 500                         Price, Quality      Weekly Retail Store                                           Social Media (Facebook, Instagram)                                    Outdoor     Maybe       7
  Male 36 and above    Retired 2000 - 4000                              Pants Ultraboost   Few times a year   RM 500 - RM 800                 Promotions, Appearance      Yearly Retail Store                                                                       Events                                 Basketball        No       8
Female        18-25    Student  Below 1000                              Pants    Ozweego       Once a month RM 1200 and above                                  Price       Daily Retail Store                                           Social Media (Facebook, Instagram)                      Jogging, Gym, Running        No       5
Female        18-25   Employee  Below 1000                              Pants Stan Smith       Once a month   RM 500 - RM 800             Appearance, Price, Quality      Weekly Retail Store                                                                       Events                                 Basketball       Yes       7
Female 36 and above    Student  Below 1000                              Shoes Stan Smith       Once a month  RM 800 - RM 1200                                  Price       Daily Retail Store                                                                       Events                                    Running     Maybe       9
Female        18-25    Student  Below 1000 Accessories (Exp : Cap, Sock, Bag)      Yeezy   Few times a year RM 1200 and above        Promotions, Appearance, Quality Fortnightly       Online                                                            Friends or Family                      Gym, Running, Jogging        No       6
  Male        26-35    Student  Below 1000                             Shirts Stan Smith   Few times a year  RM 800 - RM 1200                                Quality      Weekly Retail Store                                           Social Media (Facebook, Instagram)                               Jogging, Gym       Yes       6
  Male 36 and above    Student  Below 1000                             Shirts Ultraboost   Yearly and above   RM 500 - RM 800                      Price, Promotions       Daily       Online                                                                       Events                        Outdoor, Basketball        No       9
  Male 36 and above    Student  Below 1000                              Pants  Superstar   Few times a year RM 1200 and above                      Promotions, Price      Weekly Retail Store                                                                       Events                  Running, Jogging, Outdoor       Yes       7
Female Less than 18    Student 1000 - 2000                             Shirts Stan Smith   Yearly and above  RM 800 - RM 1200                                Quality      Yearly Retail Store                                           Social Media (Facebook, Instagram)                   Running, Basketball, Gym        No       7
  Male        18-25   Employee  Below 1000                              Shoes Ultraboost   Few times a year      Below RM 500                             Appearance      Yearly Retail Store                                                                Advertisement                            Gym, Basketball       Yes       6
Female        18-25   Employee  Above 4000                              Shoes    Ozweego   Yearly and above   RM 500 - RM 800                      Price, Appearance      Weekly Retail Store                                                            Friends or Family                                    Running        No       6
  Male        26-35   Employee  Below 1000                              Pants Stan Smith       Once a month RM 1200 and above        Promotions, Quality, Appearance       Daily Retail Store                                                            Friends or Family                               Outdoor, Gym        No       8
Female        26-35    Student  Below 1000                              Shoes      Yeezy   Few times a year   RM 500 - RM 800                                  Price Fortnightly Retail Store                                                                Advertisement                   Basketball, Jogging, Gym     Maybe       5
Female 36 and above    Student  Below 1000                              Shoes Ultraboost       Once a month      Below RM 500                             Appearance       Daily       Online                                                            Friends or Family                           Running, Outdoor       Yes       9
  Male 36 and above    Student  Below 1000                              Shoes Stan Smith Every 2 to 3 month      Below RM 500                    Quality, Promotions     Monthly       Online                                           Social Media (Facebook, Instagram)                  Outdoor, Running, Jogging        No       7
Female Less than 18    Student  Below 1000                             Shirts Ultraboost Every 2 to 3 month      Below RM 500          Promotions, Appearance, Price      Yearly       Online                                                            Friends or Family                               Gym, Outdoor       Yes       9
  Male Less than 18    Student  Below 1000                              Pants      Yeezy Every 2 to 3 month RM 1200 and above                                  Price     Monthly       Online                                                                       Events                   Gym, Running, Basketball     Maybe       9
Female        26-35    Student  Below 1000                             Shirts  Superstar       Once a month      Below RM 500                 Appearance, Promotions      Yearly Retail Store                                                                Advertisement                                    Running     Maybe       5
Female        18-25   Employee 2000 - 4000                             Shirts Ultraboost Every 2 to 3 month   RM 500 - RM 800             Price, Quality, Promotions       Daily       Online                                                                Advertisement                   Gym, Basketball, Running       Yes       6
Female        26-35    Student  Below 1000                             Shirts      Yeezy   Few times a year RM 1200 and above             Quality, Promotions, Price     Monthly       Online                                                                Advertisement                        Outdoor, Basketball       Yes       5
Female 36 and above   Employee 1000 - 2000                              Pants Stan Smith   Yearly and above      Below RM 500                             Appearance      Weekly       Online                                           Social Media (Facebook, Instagram)                      Gym, Running, Outdoor        No       5
Female Less than 18    Student 1000 - 2000 Accessories (Exp : Cap, Sock, Bag) Stan Smith   Few times a year   RM 500 - RM 800        Quality, Appearance, Promotions     Monthly       Online                                                                Advertisement                   Basketball, Running, Gym        No       8
Female 36 and above    Student  Below 1000 Accessories (Exp : Cap, Sock, Bag)    Ozweego   Few times a year  RM 800 - RM 1200                      Price, Promotions      Weekly Retail Store                                                            Friends or Family               Outdoor, Basketball, Running       Yes       8
Female        26-35   Employee  Above 4000                              Pants  Superstar   Few times a year RM 1200 and above                             Promotions      Weekly       Online                                                                       Events                               Gym, Outdoor     Maybe       6
Female 36 and above    Student  Below 1000                              Pants  Superstar Every 2 to 3 month      Below RM 500                                  Price       Daily Retail Store                                                            Friends or Family                  Running, Jogging, Outdoor        No       5
Female Less than 18    Student  Below 1000                             Shirts Stan Smith Every 2 to 3 month  RM 800 - RM 1200                    Quality, Appearance       Daily Retail Store                                                                       Events                            Basketball, Gym     Maybe       6
Female 36 and above   Employee 1000 - 2000                              Pants  Superstar       Once a month      Below RM 500             Quality, Price, Promotions       Daily Retail Store                                                                       Events                        Basketball, Outdoor        No       7
Female        26-35   Employee 1000 - 2000                              Shoes Stan Smith       Once a month RM 1200 and above                                  Price Fortnightly Retail Store                                           Social Media (Facebook, Instagram)                               Outdoor, Gym       Yes       8
Female        18-25   Employee  Above 4000                             Shirts    Ozweego       Once a month   RM 500 - RM 800             Price, Quality, Promotions      Yearly Retail Store                                                                Advertisement                      Gym, Outdoor, Running     Maybe       7
Female 36 and above    Student  Below 1000                              Pants Stan Smith   Yearly and above  RM 800 - RM 1200             Price, Appearance, Quality      Weekly       Online                                                                Advertisement                                    Outdoor        No       5
Female        18-25    Student  Below 1000 Accessories (Exp : Cap, Sock, Bag)      Yeezy   Yearly and above      Below RM 500                      Price, Appearance      Yearly       Online                                                                       Events               Basketball, Jogging, Outdoor        No       6
Female 36 and above    Student  Below 1000 Accessories (Exp : Cap, Sock, Bag)      Yeezy Every 2 to 3 month  RM 800 - RM 1200          Price, Promotions, Appearance      Weekly       Online                                                            Friends or Family               Outdoor, Running, Basketball       Yes       6
  Male        26-35    Student  Below 1000                             Shirts  Superstar Every 2 to 3 month   RM 500 - RM 800                                  Price     Monthly       Online                                                                Advertisement                                    Jogging     Maybe       8
Female        26-35    Student  Below 1000 Accessories (Exp : Cap, Sock, Bag)  Superstar   Few times a year      Below RM 500                         Price, Quality     Monthly Retail Store                                                                       Events                   Outdoor, Basketball, Gym        No       7
  Male 36 and above   Employee  Above 4000                              Pants Ultraboost       Once a month   RM 500 - RM 800                                  Price       Daily Retail Store                                                                       Events                        Basketball, Running        No       5
  Male Less than 18    Student  Above 4000                              Shoes      Yeezy       Once a month  RM 800 - RM 1200        Promotions, Appearance, Quality       Daily Retail Store                                           Social Media (Facebook, Instagram)                   Basketball, Jogging, Gym        No       7
  Male        26-35   Employee 1000 - 2000                              Shoes Ultraboost   Few times a year RM 1200 and above             Price, Appearance, Quality     Monthly       Online                                                            Friends or Family                   Jogging, Gym, Basketball        No       8
  Male        18-25    Student  Below 1000 Accessories (Exp : Cap, Sock, Bag)      Yeezy   Yearly and above      Below RM 500                                Quality       Daily Retail Store                                           Social Media (Facebook, Instagram)                                    Running        No       5
Female 36 and above   Employee  Below 1000                             Shirts Ultraboost Every 2 to 3 month  RM 800 - RM 1200             Quality, Price, Promotions     Monthly       Online                                                                Advertisement               Jogging, Basketball, Running     Maybe       5
;
run;

proc print data = myAss.table3; 	/* Print the results */
run;